# プロジェクト設定ファイル
# Project Configuration File

project:
  name: "todo-app-learning"
  created_date: "2025-06-18"

user:
  name: "takumi kumagai"

settings:
  default_language: "ja"
  timezone: "Asia/Tokyo"
  document_format: "markdown"

# メタデータテンプレート用設定
metadata_defaults:
  author: "${user.name}"